### ISSUE TITLE
Request: Enable swipe gesture to switch the control on/off

### ISSUE THREAD

**Issue by Bartzy** [abpetkov/switchery#58] opened 2015-03-11 10:42 UTC
Would be great if we can switch the control on and off by swiping left and right, just like the real iOS switch control.

**Comment by abpetkov** [comment] 2015-03-11 10:48
Duplicate of https://github.com/abpetkov/switchery/issues/36

**Closed by abpetkov** 2015-03-11 10:48 UTC

**Comment by nelsonkuang** [comment] 2016-01-26 09:05
With jQuery, I've added this feature as follows:
```javascript
            //Switchery initialization
            var init = new Switchery(document.querySelector('.js-switch'));
            setTimeout(function () {
                var _self = $(".switchery"),
                    startPos = { x: 0, y: 0 },
                    currentPos = { x: 0, y: 0 };
                var el=_self.find("small").get(0);
                el.addEventListener('touchstart', function (event) {
                    startPos = { x: event.changedTouches[0].pageX, y: event.changedTouches[0].pageY };
                }, false);
                el.addEventListener('touchmove', function (event) {
                    event.preventDefault();
                    currentPos = { x: event.changedTouches[0].pageX, y: event.changedTouches[0].pageY };
                }, false);
                el.addEventListener('touchend', function (event) {
                    currentPos = { x: event.changedTouches[0].pageX, y: event.changedTouches[0].pageY };
                    if (currentPos.x != startPos.x){
                        _self.trigger("click");//here is the key hack!
                    }
                    startPos = { x: 0, y: 0 },
                    currentPos = { x: 0, y: 0 };
                }, false);
            }, 1000);
```
