### ISSUE TITLE
how to change the disable/enable state dynamic

### ISSUE THREAD

**Issue by justein** [abpetkov/switchery#61] opened 2015-03-26 01:23 UTC
I put the switch into an grid's td as an input , all these are disabled at beginning, and when click the row,the corresponding switch becomes enabled.However I find it seems not support change state..THX!

**Comment by abpetkov** [comment] 2015-03-26 08:35
Duplicate of https://github.com/abpetkov/switchery/issues/30

**Closed by abpetkov** 2015-03-26 08:35 UTC

**Comment by justein** [comment] 2015-03-31 11:37
Finally I have fixed this problem,THX
